### ISSUE TITLE
perf-1.map & perfinfo-1.map files not available in /proc/$1/root/tmp/ folder?

### ISSUE THREAD

**Issue by paraspatidar** [joe-elliott/netcore-kubernetes-profiling#1]
Hi,
I have been working on similar  issue while i am trying to collect traces using perfcollect.
I am doing it from inside pod.
I am able to manually install those tolls and generate .trace .zip file which contains few  kbs of perf.data , however , when opening it in perfview , it doesnt show anything.

Thus landed on your git , there are few things which i need to find : 
1. How would i ssh into my K8 node.

However even before that , while checking the script , i saw that you are copying perf-1.map & perfinfo-1.map files,  however in my POD for my dotnet core process (pid=1) that folder doesnt contain these files.

instead it has files named : 
clr-debug-pipe-1-860674391-in  &  clr-debug-pipe-1-860674391-out

Thus this script will fail even if i run at node level.
am i missing something and thus .map files are not by default available ?

**Comment by joe-elliott** [comment]
Hey, thanks for the interest.  I personally am attempting to do profiling outside the container because our containers vary wildly and it would be difficult to come up with scripts or a process that worked universally.  Having said that profiling inside the container is cleaner and I think easier in a lot of ways.

> How would i ssh into my K8 node.

This will vary wildly depending on your setup.  We use kops on AWS and our nodes are in private subnets in a vpc.  That means I need access to the ssh keys that the cluster was created with and an ssh tunnel to reach into the private network.  I'm sorry, but I really can't answer this question.

> instead it has files named :
> clr-debug-pipe-1-860674391-in & clr-debug-pipe-1-860674391-out

This env var should cause netcore to generate the perf maps:
```
- name: COMPlus_PerfMapEnabled 
  value: "1"
```
are you sure it is set?

**Comment by paraspatidar** [comment]
Hi, 
Thanks for replying, yeah I went through your readme.md and found that variable set was missing during pod creation and dotnet process start as soon as pod set up ,thus files were missing.

I thought that it only works if we try to trace from outside.


However , would appreciate help on an issue :
Using perf record and perf report , i can see some output with some system library calls stack and some memory addrees.

However when using perfcollect, that zip file when created, and taken to windows machine to be viewed via perfview , then perfview doesn't  show any details.

Not sure if dotnet core containers are only good enough for perf utility and perf.core
As that tool is not able to show anything unlike flamming chart.

**Comment by joe-elliott** [comment]
If the perf maps are created and named appropriately then you should see symbols for your process.  However there is a lot of framework and runtime code that will not have symbols. 

I have successfully also been able to retrieve framework symbols using:

```
- name: COMPlus_ZapDisable
  value: "1"
```

I have not yet attempted to generate runtime symbols but if that is important to you I would start here:

https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md#getting-symbols-for-the-native-runtime
